### ISSUE TITLE
Events validation

### ISSUE THREAD

**Issue by cr0ss** [rspier/go-ecobee#8]
Seems there's not enough validation is happening with:
```
go-ecobee status
Current Settings (Away): 64.4 - 82.4.  Fan: auto
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/rspier/go-ecobee/cmd.showStatus(0xc0000c00e0, 0xc0004e7c38, 0xc0004db300)
	/Users/artemshymko/Sites/ecobee/cmd/status.go:84 +0xd40
github.com/rspier/go-ecobee/cmd.glob..func7(0x19ae960, 0x19e2508, 0x0, 0x0)
	/Users/artemshymko/Sites/ecobee/cmd/status.go:64 +0x285
github.com/spf13/cobra.(*Command).execute(0x19ae960, 0x19e2508, 0x0, 0x0, 0x19ae960, 0x19e2508)
	/Users/artemshymko/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x19ae6e0, 0x0, 0x0, 0x1)
	/Users/artemshymko/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/artemshymko/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/rspier/go-ecobee/cmd.Execute()
	/Users/artemshymko/Sites/ecobee/cmd/root.go:49 +0x31
main.main()
	/Users/artemshymko/Sites/ecobee/main.go:26 +0x95
```

**Comment by rspier** [comment]
Thanks for the bug report!
